# specify language
language: node_js

# configure which branches to run
branches:
  only:
    - master

script:
  -

deploy:
  provider: firebase
  token:
    secure: "TQYP847KO9ob86FgYSfNdhMF/9arszTTKz3DayU4xCcX0H1MjQHso9dJWPUF90vcvgDGIj3X480HYZoVAZuHoZaYxZ8mtB4Oafzcc3pcKQEZmqaYCAxYHSo9EEjozoAnNcAJ4dtkD3rt7FynLqeUmGYPVceRAyWUPB4VvtS7iYxVoMtDRiMoGmAwZrljX3GjhWYiNtxZ1sTsyEoEIaqpC8HMWoXz60ItYmznD/jd2s0oU2jFjZ+/g+ndJGSnZsJ8ZiAMUubJB742mbFOpSoXAamp96Xr//JFzHUNe+uaMzwgiTKwWjsm/acpVBuAsSZwZKr1uiofo/mMkXi2OD5qdBBztjEvpvCVhaPxJyzn6whHquqixLh62zwBZK/X/B9U0DWBFyRzuazfF2WE5iP5lwcsIGTh5yNfNzqUKEy9ZHSABQAaLy6dutXhd0nLV1+5MwqZKvCectv+u2/nqpg//5+EOin8wRFKDuePfjLqmWRUDfRffQOkdvoGGBByKSlKO4mLYOD4pyV6TYjYu8VATiU7NnI8WWjsFK25DbTvJlp8EW19NmHgeFABbHqtAPpzb300LSnnA/uDG1FtpMsMV7YSDkke3YdorRjw1G7UaQRgnE2iJFo0hgxXOVjNK0h0atx74259wyHU09fHXvBE9OcL/GbX5aKxA9VUQtVmI0Q="
  project: "thevineshdev"

# Set up notification options
notifications: 
  email:
    recipients:
      - admin@thevinesh.dev
      - roborajugr8@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
