base_config: &base_config
  docker:
    - image: circleci/node:lts
  working_directory: ~/project

version: 2
jobs:
  setup_and_install:
    <<: *base_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci
      - save_cache:
          paths:
            - ./node_modules 
          key: node-v2-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  build:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building in prod mode
          command: npm run build:prod
      - persist_to_workspace:
          root: .
          paths:
             - .


  test:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name:  Running Tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
             - .

  upload_artifacts:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: dist
          destination: public
      - persist_to_workspace:
          root: .
          paths:
             - .

  deploy:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name:  Deploy
          command: |
                    ./node_modules/.bin/firebase deploy  --non-interactive --token $FIREBASE_TOKEN
  
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup_and_install
      - build:
          requires:
            - setup_and_install
      - test:
          requires:
            - build
      - upload_artifacts:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master