base_config: &base_config
  docker:
    - image: circleci/node:lts
  working_directory: ~/project

version: 2.1
jobs:
  build_and_test:
    <<: *base_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "package-lock.json" }}
            - flutter-cache-v1-{{ checksum "pubspec.lock" }}

      - run:
          name: Installing npm Dependencies
          command: npm ci

      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
              - node_modules

      - run:
          name: Installing Flutter
          command: |
            git clone -b master https://github.com/flutter/flutter.git
            flutter/bin/flutter config --no-analytics
            flutter/bin/flutter pub get

      - save_cache:
          key: flutter-cache-v1-{{ checksum "pubspec.lock" }}
          paths:
              - .dart_tool
              - flutter

      - run:
          name: Generate code
          command: flutter/bin/flutter pub run build_runner build

      - run:
          name: Building in prod mode
          command: flutter/bin/flutter build web --release

      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
            - ./build
            - ./package.json
            - ./firebase.json
            - ./lighthouserc.json
            - ./.firebaserc
            - ./.netlify

  upload_artifacts:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .

      - store_artifacts:
          path: build/web
          destination: dist

  deploy_prod:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .

      - run:
          name:  Deploying to thevinesh.com
          command: |
            ./node_modules/.bin/firebase deploy  --non-interactive --token $FIREBASE_TOKEN

  deploy_staging:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .

      - run:
          name:  Deploying to staging
          command: |
            ./node_modules/.bin/netlify deploy -p --dir=build/web

  # change this
  create_release:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .

      - run:
          name:  Creating release
          command: |
            export VERSION=$(cat version) && npm run release

  run_lighthouse:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .

      - run:
          name:  Running Ligthouse
          command: |
            ./node_modules/.bin/lhci autorun

      - store_artifacts:
          path: .lighthouseci
          destination: ligthouse

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_and_test

      - upload_artifacts:
          requires:
            - build_and_test

      - run_lighthouse:
          requires:
            - build_and_test

      #      - create_release:
      #          requires:
      #            - build_and_test
      #            - upload_artifacts
      #          filters:
      #            branches:
      #              only: master

      - deploy_prod:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

      - deploy_staging:
          context:
            - SHARED_AUTH_TOKENS
          requires:
            - build_and_test
          filters:
            branches:
              only: develop
